// Generated by Tools/Maze/export_maze.ps1 from the Frozen Maze design (Tools/Maze). Do not edit by hand: change the
// design and export again. Cells are (column, row): column 0 is the west edge, row 0 the north edge.
#pragma once
#include "CoreMinimal.h"

namespace FrozenMazeLayout
{
inline constexpr int32 Columns = 38, Rows = 26;
struct FCell { int32 X, Y; };
// One character per cell, row by row: 0 open, 1 a wall on its east side, 2 on its south side, 3 both.
// The outer wall is always there (the last column and row are walled on their outer side).
inline const TCHAR* const Walls[Rows] = {
    TEXT("00001022023222202222222200230221000001"),
    TEXT("00001103010222010221012102103030000001"),
    TEXT("20223102110030323012321121230301222223"),
    TEXT("22221112123011010102231103022112120201"),
    TEXT("01023121202112301110203110230311210111"),
    TEXT("12301003032230131023201112101030233011"),
    TEXT("10031121102221223222232111111010210321"),
    TEXT("11211120310103000000000110121110231023"),
    TEXT("22232102113221000000000121000122121221"),
    TEXT("00222022210103000000000111011210211031"),
    TEXT("12021200131023000000000111011121123023"),
    TEXT("10212231212221000000000103312211203211"),
    TEXT("12320101023011000000000120221032122121"),
    TEXT("22103221102323000000000100210320221211"),
    TEXT("02230223220223222222222311231200012121"),
    TEXT("02101030222210021022222231011032321211"),
    TEXT("10212103102223101021010212321010031031"),
    TEXT("12301210321020302101131021012321100221"),
    TEXT("02212223023112120232223001122213203011"),
    TEXT("10222010310201212100222330320201022323"),
    TEXT("12202311202022122131010103010031100001"),
    TEXT("22232112001103101101123232100103100001"),
    TEXT("00001031232300221033102120130230200001"),
    TEXT("00000222222132022302312223103222100001"),
    TEXT("00001010201221230230230202312021100001"),
    TEXT("22223322322222223222222322222322322223"),
};
// Inner wall edges (the outer wall not counted): 744.
inline constexpr int32 InnerWalls = 744;
// Waterfall curtains: walk-through water over an open stretch of a wall line. Cell = the west (E side) or north
// (S side) cell of its first square; Length in squares.
struct FCurtain { const TCHAR* Name; FCell Cell; TCHAR Side; int32 Length; };
inline constexpr FCurtain Curtains[] = {
    {TEXT("C1"), {11, 10}, TEXT('E'), 3},
    {TEXT("C2"), {26, 8}, TEXT('E'), 3},
    {TEXT("C3"), {31, 13}, TEXT('E'), 2},
    {TEXT("C4"), {17, 17}, TEXT('S'), 2},
    {TEXT("C5"), {8, 20}, TEXT('E'), 2},
    {TEXT("C6"), {27, 21}, TEXT('S'), 2},
    {TEXT("C7"), {33, 4}, TEXT('S'), 2},
    {TEXT("C8"), {18, 0}, TEXT('E'), 1},
};
// The Deprived's lairs (shadow pools in dead ends), D1 first.
inline constexpr FCell Lairs[] = {
    {27, 0}, {12, 2}, {15, 5}, {20, 5}, {25, 6}, {6, 7}, {33, 8}, {37, 11}, {13, 14}, {29, 14}, {2, 17}, {12, 18},
    {24, 19}, {25, 21}, {28, 24}, {5, 25},
};
// Frozen remains in dead ends (smashed for Souls).
inline constexpr FCell Remains[] = {
    {7, 22}, {10, 8}, {2, 12}, {21, 17}, {30, 1}, {17, 25}, {11, 0}, {26, 14}, {8, 16}, {31, 4}, {32, 10}, {7, 1},
};
// Glow crystals at junctions.
inline constexpr FCell Crystals[] = {
    {8, 1}, {19, 25}, {36, 3}, {9, 24}, {12, 22}, {1, 3}, {23, 6}, {32, 16}, {0, 15}, {31, 1}, {12, 8}, {25, 19},
    {26, 4}, {2, 6}, {33, 11}, {12, 16}, {5, 23}, {25, 13}, {31, 25}, {31, 10}, {35, 10}, {7, 12}, {15, 1}, {24, 1},
    {17, 3}, {28, 19},
};
// Icicle traps on straight stretches of the routes to the vortex.
inline constexpr FCell Traps[] = {
    {9, 8}, {16, 0}, {24, 7}, {1, 7}, {5, 14}, {31, 11}, {16, 5}, {34, 16},
};
}
