# Writes Source/Hellgirl/Rules/FrozenMazeLayout.h from the approved design: the walls (edits.txt, gen_full.ps1), the
# waterfall curtains (curtains.txt) and the elements (elements.txt, elements.ps1). Run after changing any of them:
#   powershell -ExecutionPolicy Bypass -File Tools\Maze\export_maze.ps1
# The design is drawn on a 40 px grid starting at (40, 40): cell (column, row) = ((x - 40) / 40, (y - 40) / 40).
$ErrorActionPreference = 'Stop'
$dir = $PSScriptRoot
$header = Join-Path (Split-Path (Split-Path $dir -Parent) -Parent) 'Source\Hellgirl\Rules\FrozenMazeLayout.h'
Add-Type -Path "$dir\Cells.cs"
[Cells]::Load([string[]](Get-Content "$dir\edits.txt"))
$cols = [Cells]::W; $rows = [Cells]::H
$out = @(
    '// Generated by Tools/Maze/export_maze.ps1 from the Frozen Maze design (Tools/Maze). Do not edit by hand: change the'
    '// design and export again. Cells are (column, row): column 0 is the west edge, row 0 the north edge.'
    '#pragma once'
    '#include "CoreMinimal.h"'
    ''
    'namespace FrozenMazeLayout'
    '{'
    "inline constexpr int32 Columns = $cols, Rows = $rows;"
    'struct FCell { int32 X, Y; };'
    '// One character per cell, row by row: 0 open, 1 a wall on its east side, 2 on its south side, 3 both.'
    '// The outer wall is always there (the last column and row are walled on their outer side).'
    'inline const TCHAR* const Walls[Rows] = {'
)
$wallCount = 0
for ($r = 0; $r -lt $rows; $r++) {
    $line = ''
    for ($c = 0; $c -lt $cols; $c++) {
        $s = [Cells]::Sides($c + $r * $cols)
        $v = $(if ($s[0] -lt 0) { 1 } else { 0 }) + $(if ($s[2] -lt 0) { 2 } else { 0 })
        if ($s[0] -lt 0 -and $c -lt $cols - 1) { $wallCount++ }
        if ($s[2] -lt 0 -and $r -lt $rows - 1) { $wallCount++ }
        $line += $v
    }
    $out += "    TEXT(`"$line`"),"
}
$out += '};'
$out += "// Inner wall edges (the outer wall not counted): $wallCount."
$out += "inline constexpr int32 InnerWalls = $wallCount;"
# Curtains: a line on the grid (in px) becomes the cell on its west or north side, the side, and how many cells it spans.
$out += '// Waterfall curtains: walk-through water over an open stretch of a wall line. Cell = the west (E side) or north'
$out += '// (S side) cell of its first square; Length in squares.'
$out += 'struct FCurtain { const TCHAR* Name; FCell Cell; TCHAR Side; int32 Length; };'
$out += 'inline constexpr FCurtain Curtains[] = {'
foreach ($l in Get-Content "$dir\curtains.txt") {
    $name, $v = $l.Split(' '); $v = @($v.Split(',') | ForEach-Object { [int]$_ })
    if ($v[0] -eq $v[2]) { $c = ($v[0] - 40) / 40 - 1; $r = ($v[1] - 40) / 40; $side = 'E'; $len = ($v[3] - $v[1]) / 40 }
    else { $c = ($v[0] - 40) / 40; $r = ($v[1] - 40) / 40 - 1; $side = 'S'; $len = ($v[2] - $v[0]) / 40 }
    # The curtain's edges must be open in the walls above.
    for ($k = 0; $k -lt $len; $k++) {
        $cc = $c + $(if ($side -eq 'S') { $k } else { 0 }); $rr = $r + $(if ($side -eq 'E') { $k } else { 0 })
        $s = [Cells]::Sides($cc + $rr * $cols)
        if (($side -eq 'E' -and $s[0] -lt 0) -or ($side -eq 'S' -and $s[2] -lt 0)) { throw "Curtain $name is walled at cell $cc,$rr" }
    }
    $out += "    {TEXT(`"$name`"), {$c, $r}, TEXT('$side'), $len},"
}
$out += '};'
# Elements: cell centres in px (x = 60 + 40 * column).
$kinds = [ordered]@{ D = 'Lairs'; R = 'Remains'; G = 'Crystals'; T = 'Traps' }
$notes = @{ D = 'The Deprived''s lairs (shadow pools in dead ends), D1 first.'; R = 'Frozen remains in dead ends (smashed for Souls).'
    G = 'Glow crystals at junctions.'; T = 'Icicle traps on straight stretches of the routes to the vortex.' }
$elements = @(Get-Content "$dir\elements.txt" | ForEach-Object { , $_.Split(' ') })
foreach ($k in $kinds.Keys) {
    $out += "// $($notes[$k])"
    $out += "inline constexpr FCell $($kinds[$k])[] = {"
    $cells = @($elements | Where-Object { $_[0] -eq $k } | ForEach-Object { "{$(([int]$_[2] - 60) / 40), $(([int]$_[3] - 60) / 40)}" })
    for ($i = 0; $i -lt $cells.Count; $i += 12) { $out += '    ' + (($cells[$i..([math]::Min($i + 11, $cells.Count - 1))]) -join ', ') + ',' }
    $out += '};'
}
$out += '}'
[IO.File]::WriteAllLines($header, [string[]]$out)
"wrote $header ($wallCount inner walls, $((Get-Content "$dir\curtains.txt").Count) curtains, $($elements.Count) elements)"
